// Code generated by MockGen. DO NOT EDIT.
// Source: ./3_mocking/foo.go

// Package module3 is a generated GoMock package.
package module3

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFooInterface is a mock of FooInterface interface.
type MockFooInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFooInterfaceMockRecorder
}

// MockFooInterfaceMockRecorder is the mock recorder for MockFooInterface.
type MockFooInterfaceMockRecorder struct {
	mock *MockFooInterface
}

// NewMockFooInterface creates a new mock instance.
func NewMockFooInterface(ctrl *gomock.Controller) *MockFooInterface {
	mock := &MockFooInterface{ctrl: ctrl}
	mock.recorder = &MockFooInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFooInterface) EXPECT() *MockFooInterfaceMockRecorder {
	return m.recorder
}

// GetMessage mocks base method.
func (m *MockFooInterface) GetMessage(id int64) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", id)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockFooInterfaceMockRecorder) GetMessage(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockFooInterface)(nil).GetMessage), id)
}

// Sum mocks base method.
func (m *MockFooInterface) Sum(a, b int64) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sum", a, b)
	ret0, _ := ret[0].(int64)
	return ret0
}

// Sum indicates an expected call of Sum.
func (mr *MockFooInterfaceMockRecorder) Sum(a, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum", reflect.TypeOf((*MockFooInterface)(nil).Sum), a, b)
}
